### ISSUE TITLE
$("input").blur() causing issues when textbox has focus in Chrome v33.0.1750.154

### ISSUE THREAD

**Issue by madannes** [CarlRaymond/jquery.cardswipe#1]
Only seeing initial %B in parser. Removing that $("input").blur() line of code fixes the issue.

**Comment by JamoCA** [comment]
According to JQMigrate 3.0.1, the jQuery.fn.blur() event shorthand is deprecated.  jQuery advises that `blur()` be updated to use `trigger('blur')` instead.

Should this be reported and opened as a new issue?
