### ISSUE TITLE
Example of card readers and cross device compatibility

### ISSUE THREAD

**Issue by xandrox22001** [CarlRaymond/jquery.cardswipe#10]
Hi,

Sorry to write this as an issue but I didn't know how else I could ask you this ...

I wanted to ask if you are able to give some examples/recommend of good credit card readers that you worked in the past but also, is it possible to use javascript on an IOS or Android device that would be connected to a card reader - through bluetooth or that jack -, or the keyboard mimic is only possible on computers ?

Thank you in advance !

Regards,
Dan

**Comment by CarlRaymond** [comment]
Dan,
 I don't have any experience with bluetooth readers for tablets. A quick web search found one that came with an API download. That suggests that it's not just acting as a keyboard, although possibly it could do that as well. The plugin will only work with the keyboard-emulating devices.

You may be able to attach a USB reader to an Android tablet with an adapter cable.

I have an AGPtek USB 2.0 All-in-One Card Reader, which is a simple USB reader. I've had no trouble with it.

Regards,
Carl
