### ISSUE TITLE
Not getting data in form fields

### ISSUE THREAD

**Issue by eduardomart** [CarlRaymond/jquery.cardswipe#11]
I am succesfully scanning a card and I see the green overlay with the correct card data but the overlay pops up twice and afterwards the data is not populated into the form fields.  Using the demo file that comes with the package.

Tried Safari/Firefox/Chrome.

Am I missing something?

**Comment by eduardomart** [comment]
I think the problem is that you declare var = success twice

**Comment by CarlRaymond** [comment]
I believe you're right. Formerly there was a "complete" callback and a "success" event, but "complete" got renamed to "success". Will fix.
