### ISSUE TITLE
Readers

### ISSUE THREAD

**Issue by kikozik** [CarlRaymond/jquery.cardswipe#14]
I took a couple of magnetic card readers that were made for smart phones. One from FirstData, another from AnywhereCommerce. Pligged them into iPhone's phone jack; both didn't seem to work on iOS in either Safari or Chrome using your demo page. I also ordered a couple of chinese generic magnetic readers from Amazon but they didn't arrive yet, so I can't tell if those will work or not. In general, do those phone card readers have to be of a certain type? Thanks!

**Comment by CarlRaymond** [comment]
The plugin expects to see keyboard events, from readers that simulate a keyboard. A reader made for smartphones may not work that way -- it could have an API that you can get to with an app, but not from a web site. This project is intended for web sites. Have a look at this comment in another issue: https://github.com/CarlRaymond/jquery.cardswipe/issues/13#issuecomment-191996504
The writer describes using a USB-to-Lightning connector with a USB reader, and it works.
