### ISSUE TITLE
Discover Network

### ISSUE THREAD

**Issue by treed593** [CarlRaymond/jquery.cardswipe#21]
Are there plans to add the Discover Network RegEx, or can someone assist in writing the parser

**Comment by CarlRaymond** [comment]
There is a Discover parser already, though the demo page, demo-simple.html, doesn't use it. You could modify line 63 to this:
`parsers: [ "visa", "mastercard", "amex", "discover", "generic" ],`
Then it should recognize them. The regular expression pattern I used is very simple; it looks for a 16-digit number starting with a 6. I don't have that card myself, so I can't easily test it.

I'll update it shortly to include that change.

**Comment by treed593** [comment]
Its strange, because when I installed the library from NPM, don't know if that is deprecated or what, Discover was not included. I actually ended up copying the visa parser and changing the length and starting digit to work with Discover. Thanks for the quick response

**Comment by CarlRaymond** [comment]
You know what, I may not have republished it on NPM after adding the Discover parser. If you get the latest straight from Master, it's there, and a unit test for it. Possibly you have an older version.

**Comment by treed593** [comment]
I will pull in the version from master, but I did see the parser is in Master. Thanks for your help. This is an awesome project that was super easy to use

**Comment by CarlRaymond** [comment]
I have updated NPM with the latest version, 1.2.0, which includes the Discover parser in the sample pages.
