### ISSUE TITLE
How to get CVV number?

### ISSUE THREAD

**Issue by shafiqhossain** [CarlRaymond/jquery.cardswipe#26]
I see it returns card number, first name, last name, expire month and year. How can i get CVV number?

**Comment by danilovdmitry** [comment]
@shafiqhossain as far as I know, credit card readers/swipers don't provide cvc/cvv number in data string. So you need to paste cvc/cvv number manually.

**Comment by CarlRaymond** [comment]
That is correct. The CVV isn't in the magnetic stripe data at all.
