### ISSUE TITLE
success.cardswipe is not getting called

### ISSUE THREAD

**Issue by karpitpatel** [CarlRaymond/jquery.cardswipe#28]
I can succesfully swipe the card. I got the alertbox with data at Line 2.
but after that success.cardswipe is not getting called. I want to call an ajax call after succesfully swipe the card. I have not fired npm install or any kind if node thing. I want to do without node.js. only pure jquery.
 I am not keeping gruntfile.js in my project

**Comment by CarlRaymond** [comment]
Have you passed in your success function in the configuration? See demo-simple.html at line 60.

Do you also have an error function? On a card swipe, either the success or error function should be invoked. If neither is invoked, it could be a configuration error. If the error callback is called, your custom parser isn't recognizing the card.

You can use the plugin without Node. Just use one of the files in the dist folder.

**Comment by karpitpatel** [comment]
Successfully got the event being called via demo-event.cshtml page. 
Thanks!!!!
