### ISSUE TITLE
Project license missing

### ISSUE THREAD

**Issue by antch** [CarlRaymond/jquery.cardswipe#6]
What's the license on this project?  Can you please include some license text in the source?

**Comment by antch** [comment]
I'm seeing now that the license is referenced in `cardswipe.jquery.json`.  It would still be helpful to have it as a comment in the `.js` file or `LICENSE.md`.  Also, are you open to a more permissive license than GPLv2?

**Comment by edmistj** [comment]
+1 Love your component but would you be able to release it under an Apache or MIT license to allow it to be used in other open-source projects with these more permissive licenses?

**Comment by CarlRaymond** [comment]
At the moment, I'm not inclined to change the license.  My intent is that this stay an independent jQuery plugin. Any other plugin could of course build on it.

**Comment by antch** [comment]
I respect that, however please note that by many interpretations GPLv2 is a viral license in that a software application which merely uses your plugin (without modifying the source) would be required to provide the source to that entire application.  This is in contrast to the LGPL, which specifically makes concessions for usage of software as a "library" (while still requiring modifications to be open-sourced).  

From your comment it sounds like this license would be more in-line with what you're trying to achieve, so I thought that I would throw it out there.

**Comment by edmistj** [comment]
@CarlRaymond Thanks for the response. Just to clarify, we would want your component to remain independent. We would like to use it as a part of our open-source CMS system (www.rockrms.com). Since we release under an Apache license we could not include components licensed under GPL.  

Just wanted to clarify our thoughts.
