### ISSUE TITLE
Works with IE 11, Firefox, Safari but not IE10

### ISSUE THREAD

**Issue by gunther2783** [CarlRaymond/jquery.cardswipe#7]
I am facing issues where this solution works perfectly on safari, firefox, IE 11 but not on IE10.

Has anyone come across this issue before and would you by any chance find a solution for it?

**Comment by gunther2783** [comment]
Found the problem...just take the last comma ( , ) out of the code below...it has too many comma.


	// Defaults for settings
	var defaults = {
		enabled: true,
		interdigitTimeout: 250,
		success: defaultSuccessCallback,
		error: null,
		parser: defaultParser,
		firstLineOnly: false,
		prefixCharacter: null,
		debug: false,  <<<<<<<<<--------- remove comma
	};

**Comment by CarlRaymond** [comment]
Fixed on "events" branch.
